owner: TheAPIGuysDev
repo: triviaties-status

sites:
  - name: Triviaties Web
    url: https://triviaties.com/
  - name: Triviaties App
    url: https://app.triviaties.com/
  - name: BigQuizThing Web
    url: https://playbigquiz.com/
  - name: Triviaties API (ping)
    url: https://api.triviaties.com/ping/
    expectedStatusCodes: [200]
  - name: Triviaties API (readiness)
    url: https://api.triviaties.com/healthz/
    expectedStatusCodes: [200]

status-website:
  cname: status.triviaties.com
  name: Triviaties Status
  introTitle: Triviaties system status
  introMessage: Real-time status of Triviaties services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/TheAPIGuysDev/triviaties-status

assignees:
  - brumiser1550
